
import { Student, Coach } from './types';

export const FORMS = [
  '1 BALADA', '1 JAZZ', '1 TANGO',
  '2 ZAPIN', '2 INANG', '2 MASRI',
  '3 BONEKA', '3 BANGSAWAN', '3 MUZIKAL',
  '4 CINDAI', '4 SUTERA', '4 SONGKET',
  '5 BUDAYAWAN', '5 KARYAWAN', '5 SENIMAN'
];

export const FIELDS = ['MUZIK', 'VISUAL', 'TARI', 'TEATER'];
export const GENDERS = ['LELAKI', 'PEREMPUAN'];
export const GROUPS = [
  '1 PANGGUNG', '1 GEMERSIK', '1 TAMPAK', '1 GEMALAI',
  '2 PANGGUNG', '2 GEMERSIK', '2 TAMPAK', '2 GEMALAI',
  '3 PANGGUNG', '3 GEMERSIK', '3 TAMPAK', '3 GEMALAI', '3 BAIDURI',
  '4 TEATER', '4 MUZIK', '4 VISUAL', '4 TARI',
  '5 TEATER', '5 MUZIK', '5 VISUAL', '5 TARI'
];

export const TIME_SLOTS = [
  '8:00 - 11:00',
  '8:30 - 12:00',
  '12:30 - 16:00'
];

export const ROOMS = [
  'Studio Muzik Tradisional',
  'Studio Keyboard 1',
  'Studio Keyboard 2',
  'Studio Orkestra',
  'Studio Individu'
];

export const COACHES: Coach[] = [
  { name: "MOHD DZURRI BIN BACHOK", field: "BIDANG SENI MUZIK" },
  { name: "AHMAD NAZRI BIN NORDIN", field: "BIDANG SENI MUZIK" },
  { name: "MUHAMMAD SYAHIR BIN MUHAMMAD JOHRI", field: "BIDANG SENI MUZIK" },
  { name: "NORHAFIZZUL BIN ZULKIFLI", field: "BIDANG SENI MUZIK" },
  { name: "NOOR FAIZ BIN JAFFAR", field: "BIDANG SENI MUZIK" },
  { name: "MOHD NAJIB BIN JAAFAR", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "TEE TIAM CHAI", field: "PENTADBIRAN" },
  { name: "ARINA IRRISYA BINTI ALIFF ISKANDAR KHOR", field: "BIDANG BAHASA" },
  { name: "MOHAMMAD ISMAIL BIN TAHA", field: "BIDANG BAHASA" },
  { name: "SITI JAUHARA BINTI JAMIAN", field: "PENTADBIRAN" },
  { name: "MUHAMAD SAFIDZAN BIN SALMAN", field: "PENTADBIRAN" },
  { name: "KHAIRINA BT WAHLED @ WALID", field: "PENTADBIRAN" },
  { name: "IZU HANA ZILZA BINTI IMRAN", field: "BIDANG SENI TEATER" },
  { name: "MAH NYUK YING", field: "PENTADBIRAN" },
  { name: "NUREMELIA BINTI MOHAMAD RAWAN", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "NURUL INZAH BINTI WAN ZIN", field: "BIDANG BAHASA" },
  { name: "NURATIKAH BINTI ATAN", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "NUR AZLIN BINTI JALIL", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "ZARAMILA BINTI SALIM", field: "BIDANG BAHASA" },
  { name: "SITI RAHAYU BINTI MESNAI", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "SARAVANAN A/L PALANISAMY", field: "BIDANG BAHASA" },
  { name: "MUHAIDIR BIN MOHAMAD", field: "BIDANG BAHASA" },
  { name: "DALILA AYU BINTI ADAN", field: "BIDANG BAHASA" },
  { name: "MUHAMMAD SHAKIFF BIN AMAT BASRI", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "SITI AKMAL RUHI BT SYEIKH ABDUL GHAFAR", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "MAZLITA BINTI MD SALLEH", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "NURULAIN BINTI NARDIR", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "MOHD FIRDAUS BIN MOHD JALIL", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "ROZIDALINA BINTI ABDULLAH", field: "BIDANG SENI VISUAL" },
  { name: "FAEZAH BINTI BAHARI", field: "BIDANG SENI VISUAL" },
  { name: "NOR SOLEHA LAILA BINTI NASIMIN", field: "BIDANG SENI MUZIK" },
  { name: "MUHAMAD FARIF BIN MARLIAS", field: "BIDANG SENI TARI" },
  { name: "MOHAMAD NIZAM BIN MOHD YAMIN", field: "BIDANG SENI TEATER" },
  { name: "SITI BADARIAH BINTI ZAITON", field: "BIDANG SENI TEATER" },
  { name: "ANIZA BINTI JALAL", field: "BIDANG SENI TEATER" },
  { name: "SITI FARDOAS IZATI BINTI AHMAD", field: "BIDANG SENI TEATER" },
  { name: "KANA ANAK JANA", field: "BIDANG SENI TARI" },
  { name: "FAZRIZZAL BIN HUDZURI", field: "BIDANG SENI TARI" },
  { name: "SITI NUR UL NAQUIAH BINTI MOHAMAD ISMAIL", field: "BIDANG SENI TEATER" },
  { name: "MUHAMMAD FAIQ BIN MAT RANI", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "MAULIDIYA BINTI UMAR LAYEM", field: "BIDANG SAINS KEMASYARAKATAN" },
  { name: "AMALINA BINTI GHAZALI", field: "BIDANG BAHASA" },
  { name: "SITI NUR HAFIZAH BINTI ABDUL LATIF", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "NIZAM BIN RUSLI", field: "BIDANG SENI MUZIK" },
  { name: "MOHAMMAD HAZIQ BIN MAT RIPING", field: "BIDANG SENI MUZIK" },
  { name: "HASYANTI BINTI HASHIM", field: "BIDANG BAHASA" },
  { name: "SITI SALINA BINTI AB GHANI", field: "BIDANG SENI VISUAL" },
  { name: "SITI NASUHA BINTI KHAIRUDDIN", field: "BIDANG SENI VISUAL" },
  { name: "NOR ALISA BINTI JAMALUDDIN", field: "BIDANG SENI VISUAL" },
  { name: "NOOR YUNIZZA BINTI BAHAR", field: "BIDANG SENI VISUAL" },
  { name: "MOHD FAUZI BIN AHMAD SELO", field: "BIDANG SENI TARI" },
  { name: "NURUL SYAHIRAH BINTI RAZALI", field: "BIDANG SENI VISUAL" },
  { name: "AMIRA NATASYA BINTI OTHMAN", field: "BIDANG SENI TARI" },
  { name: "NOR SYAZANA BINTI ABD GHANI", field: "BIDANG SENI TEATER" },
  { name: "NURJANNAH BINTI BERHANNUDIN", field: "BIDANG SAINS DAN MATEMATIK" },
  { name: "NAJWA BINTI DAUD", field: "BIDANG SENI MUZIK" },
  { name: "NOR HIDAYAH BINTI HAYON", field: "BIDANG SENI TARI" },
  { name: "MUHAMMAD HAIRI BIN ABDUL RAHIM", field: "BIDANG SENI VISUAL" }
];

export const INITIAL_STUDENTS: Student[] = [
  { id: "1", name: "ABU SHAFWAN BIN ABU SUFIAN", gender: "LELAKI", form: "3 BONEKA", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "2", name: "ADAM HAKIMI BIN ALEF", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "3", name: "AFEEF RAYYAN KHILFI BIN ZULKARNAIN", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "4", name: "AMMAR HAFIDZI BIN SAIDI", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "5", name: "IMAN BIN ABDUL RAZAK", gender: "LELAKI", form: "3 BONEKA", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "7", name: "MAHIR DARIS DANIAL BIN MAHIR AFENDI", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "8", name: "MUHAMAD RAYYAN SYAZWAN BIN IZUAN", gender: "LELAKI", form: "3 MUZIKAL", group: "3 PANGGUNG", field: "TEATER" },
  { id: "9", name: "MUHAMMAD ADAM HARITH BIN ABDULLAH", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "10", name: "MUHAMMAD IQRAM HAZRIQ BIN SELEH", gender: "LELAKI", form: "3 BONEKA", group: "3 GEMALAI", field: "TARI" },
  { id: "11", name: "AIN NURSYIFA BINTI MOHAMAD IKHRAM", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "12", name: "AISYAH SUMAYYAH BINTI ZULKEPLY", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "13", name: "AMEERA SOFEA BINTI AMRIL", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "14", name: "CHARICE EVE HENRY", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "15", name: "CHINTA SURI EOWYN BINTI ZULKIFLI", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "16", name: "IMAN QAISARA BINTI MOHAMMAD HAFIZ", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "17", name: "NUR AIRISSA BINTI MOHD ASRIZAN", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "18", name: "NUR DAMIA BATRISYIA BINTI MOHD YAZID", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "19", name: "NUR FATINI QISYA BINTI AHMAD FUAD", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "20", name: "NUR SAFFIYA QAISARA BINTI YAZID", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "21", name: "NUR ZAFIRAH BINTI YUSRI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "22", name: "NURUL DHIA IMAN BINTI ISMAIL", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "23", name: "SITI AISYAH BINTI ESA", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMALAI", field: "TARI" },
  { id: "24", name: "YAP MIN ENN", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 BAIDURI", field: "VISUAL" },
  { id: "25", name: "ZARA SUFYA BINTI ZALMAIZIZI", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "26", name: "ASHRULL BENJYMIN BIN SHAHRIL", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "27", name: "IMRAN HAILMY BIN MUSTAFAKAMAL", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 PANGGUNG", field: "TEATER" },
  { id: "28", name: "MOHAMAD HARRIS NUFAIL BIN ZAMBROSSE", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "29", name: "MUHAMMAD AMAL ANAQI BIN MOHD ARIF", gender: "LELAKI", form: "3 MUZIKAL", group: "3 TAMPAK", field: "VISUAL" },
  { id: "30", name: "MUHAMMAD AQIL HASIF BIN YUSZRI", gender: "LELAKI", form: "3 BONEKA", group: "3 GEMALAI", field: "TARI" },
  { id: "31", name: "WAN HAIYL MAJID BIN WAN MOHD RAYZUDDIN", gender: "LELAKI", form: "3 MUZIKAL", group: "3 PANGGUNG", field: "TEATER" },
  { id: "32", name: "ALYA DAMIA BINTI MOHD SHAH REDZA", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "33", name: "AMNA NURHUSNA BINTI MOHD YAZIR", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "34", name: "JELITA JUWITA AISYAH BINTI ELYSA NIZAL", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMALAI", field: "TARI" },
  { id: "35", name: "MIEYA KHYRRA ELYENA BINTI MOHD HAZLIMIE", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMALAI", field: "TARI" },
  { id: "36", name: "NIK HANNAH BATRISYIA BINTI NIK AZRUL", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "37", name: "NUR ALIYA ARISSA BATRISYIA MAISARAH BINTI JAMAL AB NASIR", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 PANGGUNG", field: "TEATER" },
  { id: "38", name: "NUR ALYA BATRISYIA BINTI MOHD HELMI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "39", name: "NUR ERYNA SOFIA BINTI DICKY SOPHIAN", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "40", name: "NUR HAWA SAFIYYA BINTI MOHAMED SHAIFULLIZA", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "41", name: "NUR QAIREEN SYAHMINA BINTI MOHD SHUHAIMI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 GEMALAI", field: "TARI" },
  { id: "42", name: "NUR QISTINA BINTI MOHD FAIZUL", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "43", name: "NUR SYALIA HANIES BINTI SAIFUL ELMEE", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "44", name: "ADAM QALLEF BIN MOHD ZAWAWI", gender: "LELAKI", form: "3 MUZIKAL", group: "3 PANGGUNG", field: "TEATER" },
  { id: "45", name: "AHMAD NABIL BIN AZLAN", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 PANGGUNG", field: "TEATER" },
  { id: "46", name: "AKASHA BAKRI BIN MOHD HAIRUL BAHARUDDIN", gender: "LELAKI", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "47", name: "DZAKIR IRFAN BIN RAMLEE", gender: "LELAKI", form: "3 BONEKA", group: "3 PANGGUNG", field: "TEATER" },
  { id: "48", name: "FAIZ HAKIM BIN MOHD FAZLY", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "49", name: "FIRDAUS SAFWAN BIN HAIZUL IZAT", gender: "LELAKI", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "50", name: "MUHAMMAD DARWISH BIN AZMI", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "51", name: "MUHAMMAD FIRAS FURQAN BIN MUHAMAD FIRDAUS", gender: "LELAKI", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "52", name: "MUHAMMAD ZIQRI NASHRULLAH BIN MOHD ZAMRI", gender: "LELAKI", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "53", name: "RAYKAL MIKAIL BIN ABDULLAH", gender: "LELAKI", form: "3 BANGSAWAN", group: "3 GEMALAI", field: "TARI" },
  { id: "54", name: "AMINAH BATRISYA BINTI AZHARUDDIN", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "55", name: "ARIANA BINTI AZARI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 TAMPAK", field: "VISUAL" },
  { id: "56", name: "FATNIN SOFEA BINTI FAKHRI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "57", name: "HANI SOFEA BINTI SHAHRUL AFFENDY", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 PANGGUNG", field: "TEATER" },
  { id: "58", name: "HANIS HANANNI BINTI MOHD HAZARIS", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 TAMPAK", field: "VISUAL" },
  { id: "59", name: "NUR ATHIRAH BINTI AHMAD MAZLI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 PANGGUNG", field: "TEATER" },
  { id: "60", name: "NUR AZURA BINTI BAKERI", gender: "PEREMPUAN", form: "3 BONEKA", group: "3 GEMALAI", field: "TARI" },
  { id: "61", name: "NUR IRIS AWATIF BINTI ROSEDLLY", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMALAI", field: "TARI" },
  { id: "62", name: "NURUL IMAN ARISSA BINTI NORYADI", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 TAMPAK", field: "VISUAL" },
  { id: "63", name: "QISYA MIASARA BINTI SAHRIAFENDY", gender: "PEREMPUAN", form: "3 MUZIKAL", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "64", name: "SUFHA ARIANNA BINTI MUHAMAD ALI", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 GEMERSIK", field: "MUZIK" },
  { id: "65", name: "ZARA NOUR ISLAM BINTI ZAHAREL", gender: "PEREMPUAN", form: "3 BANGSAWAN", group: "3 PANGGUNG", field: "TEATER" },
  { id: "67", name: "AMMAR IFTIKHAR SHAH BIN IRWAN SHAH", gender: "LELAKI", form: "4 CINDAI", group: "4 TARI", field: "TARI" },
  { id: "68", name: "IDHAM ISKANDAR BIN HAIRIZADT", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "69", name: "MUHAMAD FARHAN BIN ZAHARUN HISHAM", gender: "LELAKI", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "70", name: "MUHAMMAD ADAM FIRAZ BIN AMIRUDDIN", gender: "LELAKI", form: "4 CINDAI", group: "4 TEATER", field: "TEATER" },
  { id: "71", name: "MUHAMMAD DAILAMI HAIL BIN MOHD NURULLAIL", gender: "LELAKI", form: "4 SONGKET", group: "4 VISUAL", field: "VISUAL" },
  { id: "72", name: "MUHAMMAD HAFIZ HIDAYAT BIN SHARUDIN", gender: "LELAKI", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "73", name: "MUHAMMAD JOHARI HAFIZI BIN MOHD TARMIZI", gender: "LELAKI", form: "4 CINDAI", group: "4 MUZIK", field: "MUZIK" },
  { id: "74", name: "TAN IRO", gender: "LELAKI", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "75", name: "AUNI AWATIF BINTI HAIRUN MAHADZIR", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TARI", field: "TARI" },
  { id: "76", name: "CAHAYA BATRISYA BINTI LOKMAN ALHAKIM", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "77", name: "DAMIA HANNAH BINTI MOHAMAD ARIFF", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 MUZIK", field: "MUZIK" },
  { id: "78", name: "KASEH QAISARA BINTI KAMARUL ARIFIN", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 MUZIK", field: "MUZIK" },
  { id: "79", name: "NUR AINA ASYIKIN BINTI JEHAN", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "80", name: "NUR AYRA NISA BINTI AHMAD NIZAM", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "81", name: "NUR NAZREEN AIDREESYA BINTI MOHD NAZRON", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TEATER", field: "TEATER" },
  { id: "82", name: "SUFIYA BINTI MOHD.AZRIEN HAFFIZ", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 VISUAL", field: "VISUAL" },
  { id: "83", name: "WAN NUR DINIE MAWADDAH BINTI WAN MOHAMAD ASRAN", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TEATER", field: "TEATER" },
  { id: "84", name: "AHMAD AIMAN ZAKWAN BIN KURNIA BUDI", gender: "LELAKI", form: "4 SONGKET", group: "4 VISUAL", field: "VISUAL" },
  { id: "85", name: "MOHAMAD ADAM RAYYAN BIN HERIYANTO", gender: "LELAKI", form: "4 SUTERA", group: "4 TEATER", field: "TEATER" },
  { id: "86", name: "MUHAMMAD ASRIQ ISYRAQ BIN SAIFUL RIZAL", gender: "LELAKI", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "87", name: "MUHAMMAD BAIHAQI HAKIMI BIN MOHD ROZAIMI", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "88", name: "MUHAMMAD SHAHIRFAN BIN SAHRIZAN", gender: "LELAKI", form: "4 SUTERA", group: "4 VISUAL", field: "VISUAL" },
  { id: "89", name: "RADEN MIRZA BIN MUHAMMAD", gender: "LELAKI", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "90", name: "WAN MUHAMMAD HADIF FIRDAUS BIN WAN MD KHAIRUDDIN", gender: "LELAKI", form: "4 SONGKET", group: "4 VISUAL", field: "VISUAL" },
  { id: "91", name: "AIRA ARIESHA BINTI NURZURIALIS", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TARI", field: "TARI" },
  { id: "92", name: "AUNI NUR QASEH BINTI MOHD AIRI", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "93", name: "INTAN AMIRA BATHRISYA BINTI ABDUL RAHMAN", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "94", name: "NOR ARAFAH BINTI MOHAMAD SHARIFFUDIN", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 VISUAL", field: "VISUAL" },
  { id: "95", name: "NUR ALYA AMANI BINTI AZAHAR", gender: "PEREMPUAN", form: "4 SUTERA", group: "4 TARI", field: "TARI" },
  { id: "96", name: "NURFATIHAH ZULAIKHA BINTI MOHD AZLAN", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 MUZIK", field: "MUZIK" },
  { id: "97", name: "NURJANNAH NAJWA BINTI MD MASIKAH", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "98", name: "NURMIA AMANI BINTI MUHAMMAD ZAIRUL", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "99", name: "NURUL AIN SYAZANA BINTI RAHIM", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TARI", field: "TARI" },
  { id: "100", name: "NURUL AQILAH BINTI SULAIMAN", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TARI", field: "TARI" },
  { id: "101_2", name: "QASEH QAIREEN BINTI MOHD ROSDI", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TEATER", field: "TEATER" },
  { id: "102_2", name: "SITI SOLEHAH BINTI ARIFF FAISAL", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "104_2", name: "AFNAN ZHAHRAN BIN MOHD KAMARUL AZMAN", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "105_2", name: "AN NUR NADZIF BIN MOHAMAD LOKMAN", gender: "LELAKI", form: "4 SONGKET", group: "4 MUZIK", field: "MUZIK" },
  { id: "106_2", name: "LUQMAN HAKIM BIN HAIZUL IZAT", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "107_2", name: "MOHAMAD SHUKRI BIN SHAHRUDDIN", gender: "LELAKI", form: "4 SUTERA", group: "4 TEATER", field: "TEATER" },
  { id: "108_2", name: "MUHAMMAD AMIN NAUFAL BIN HAMIRUL FARID", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "110_2", name: "MUHAMMAD DANISH QHAYRI BIN HALIL", gender: "LELAKI", form: "4 SUTERA", group: "4 TEATER", field: "TEATER" },
  { id: "111_2", name: "SYARAZY RAYYAN BIN SYAMSUL SYAZWAN", gender: "LELAKI", form: "4 SUTERA", group: "4 MUZIK", field: "MUZIK" },
  { id: "112_2", name: "AISY DAMIA BINTI MOHD KAMAL ARIFFIN", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "113_2", name: "AISYAH NUR HANNAH BINTI AZAM", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 TEATER", field: "TEATER" },
  { id: "114_2", name: "AL QHALISHA IMAN BINTI AHMAD RIDUAN", gender: "PEREMPUAN", form: "4 CINDAI", group: "4 VISUAL", field: "VISUAL" },
  { id: "115_2", name: "ANIS FATIMAH BINTI ISMAIL", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TARI", field: "TARI" },
  { id: "116_2", name: "AZWAJILLA NUR SYIFA BINTI MOHD UYUB", gender: "PEREMPUAN", form: "4 SUTERA", group: "4 TARI", field: "TARI" },
  { id: "118_2", name: "NUR BATRISYA QUSYTIKA BINTI ABDUL HAKIM", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 TEATER", field: "TEATER" },
  { id: "119_2", name: "PUTERI MARISSA BINTI MUHAMMAD TAIB", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 MUZIK", field: "MUZIK" },
  { id: "120_2", name: "RAISHA QISTINA BINTI SHAHIFUZIE", gender: "PEREMPUAN", form: "4 SUTERA", group: "4 TEATER", field: "TEATER" },
  { id: "121_2", name: "WAN FATNIN ARISSA BINTI WAN AZROL", gender: "PEREMPUAN", form: "4 SUTERA", group: "4 TEATER", field: "TEATER" },
  { id: "122_2", name: "ZARITH ZARA SOFEA BINTI AZLAN", gender: "PEREMPUAN", form: "4 SONGKET", group: "4 MUZIK", field: "MUZIK" },
  { id: "123", name: "ADAM ASHRAF BIN SUHAIRUDIN", gender: "LELAKI", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "124", name: "MAHAAWIN AL SIVAMOHAN", gender: "LELAKI", form: "5 KARYAWAN", group: "5 TEATER", field: "TEATER" },
  { id: "125", name: "MUHAMMAD DINIE FAYYADH BIN MUHAMAD FAIZAL", gender: "LELAKI", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "126", name: "MUHAMMAD ELHAM BIN EZIHAN", gender: "LELAKI", form: "5 BUDAYAWAN", group: "5 TEATER", field: "TEATER" },
  { id: "127", name: "ADLINA QAISARA BINTI ADLY FARID", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "128", name: "ALLYSHA BATRISYIA BINTI ZULKEFLI", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "129", name: "A'SHADIEYAH ARTA BINTI FAIZAL", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "130", name: "AUNI KARMILA BINTI RABI", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "131", name: "AVELYNN EISHA BINTI ZULHISHAM", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "132", name: "ELYSHA BINTI DARREL", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "133", name: "FATNIN IJLAH HANNAH BINTI SAIFUL BAHRI", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "134", name: "INTAN SHAFIQAH SYAUQINA BINTI JULAINI", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "135", name: "KAISAH LATIIFAH BINTI OMAR", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 TARI", field: "TARI" },
  { id: "136", name: "NIK JASMINE ZULAIKA BINTI NIK HASRULWADI", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 TEATER", field: "TEATER" },
  { id: "137", name: "NUR AISYAH BINTI MOHD ZAIDI", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "138", name: "NUR AMALIN BINTI IBRAHIM", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "139", name: "NUR RAUDHAH IRDINA BINTI AZHAR", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "140", name: "NURLIN ATHIRAH BINTI ABD MALEK", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "141", name: "QASRINA AMANI BINTI MUHAMMAD FIRDAUS", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "142", name: "SOFIA NAJIHA BINTI MUHD KHAIRUDDIN", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "143", name: "IQBAL HAKIMI BIN GHAZALI", gender: "LELAKI", form: "5 SENIMAN", group: "5 TARI", field: "TARI" },
  { id: "144", name: "MUHAMMAD AFIFFUDDIN BIN KHAMIS", gender: "LELAKI", form: "5 KARYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "145", name: "MUHAMMAD HARITH BIN MOKHTAR", gender: "LELAKI", form: "5 KARYAWAN", group: "5 TEATER", field: "TEATER" },
  { id: "146", name: "MUHAMMAD RAIYAN QAYYUM BIN MUHAMMAD RASHIDI", gender: "LELAKI", form: "5 SENIMAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "147", name: "RAYYAN ZAFFRAN BIN MUHAMMAD FIRDAUS", gender: "LELAKI", form: "5 SENIMAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "148", name: "ARWYN NIA EEVA BINTI SHAHAZRIL", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "149", name: "FARAH NURBATRISYIA BINTI MOHD GHAZALI", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 TARI", field: "TARI" },
  { id: "150", name: "MARISSA SYUHADA BINTI ROSLE", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "151", name: "MARSYA NAJIHAH BINTI SAIFULIZAN", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 TARI", field: "TARI" },
  { id: "152", name: "NUR ALIANA ZAHRA BINTI SAIFUL RIZAN", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "153", name: "NUR ARIFFAH AMEERA BINTI SAZALI", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 TARI", field: "TARI" },
  { id: "154", name: "NURFARISA INSYIRAH BINTI FARISZUL", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "155", name: "PUTERI BALQIS AZZAHRA BINTI JAYSRIL AZMER", gender: "PEREMPUAN", form: "5 BUDAYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "156", name: "UMMI SOFEA BINTI ARSHAD", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "157", name: "AMIR ARSYAD BIN AZAN", gender: "LELAKI", form: "5 KARYAWAN", group: "5 VISUAL", field: "VISUAL" },
  { id: "158", name: "HAIKAL IRFAN BIN HAIRUDIN SHAH", gender: "LELAKI", form: "5 SENIMAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "159", name: "MOHAMAD EKHRAM BIN ZAILANI", gender: "LELAKI", form: "5 SENIMAN", group: "5 TEATER", field: "TEATER" },
  { id: "160", name: "MUHAMMAD ADAM ASHRAF BIN ABDUL RAHIM", gender: "LELAKI", form: "5 SENIMAN", group: "5 TEATER", field: "TEATER" },
  { id: "161", name: "MUHAMMAD FAEZIN BIN MOHD FAISHAL", gender: "LELAKI", form: "5 KARYAWAN", group: "5 TARI", field: "TARI" },
  { id: "163", name: "MUHAMMAD NOOR AMZAR BIN AMRAN", gender: "LELAKI", form: "5 SENIMAN", group: "5 TARI", field: "TARI" },
  { id: "164", name: "MUHAMMAD RAZIQ FARHAN BIN MUHAMMAD FARID", gender: "LELAKI", form: "5 SENIMAN", group: "5 TARI", field: "TARI" },
  { id: "165", name: "MUHAMMAD YUSUF ASRI BIN JEFFERY", gender: "LELAKI", form: "5 SENIMAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "166", name: "WAN ABDURRAHIM BIN MAHAT", gender: "LELAKI", form: "5 SENIMAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "167", name: "AISHA KYRNA BINTI AHMAD SAMRI", gender: "PEREMPUAN", form: "5 SENIMAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "168", name: "AISYAH AZIZ BINTI ABDUL HALIM", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "169", name: "NUR AFRINA RAIHAN BINTI NAZERI", gender: "PEREMPUAN", form: "5 SENIMAN", group: "5 TARI", field: "TARI" },
  { id: "170", name: "NUR ALIYA ARIANA BINTI ABDUL AZIZ", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 TEATER", field: "TEATER" },
  { id: "171", name: "PUTERI ADRIANA QISTINA BINTI ANUARASID", gender: "PEREMPUAN", form: "5 SENIMAN", group: "5 MUZIK", field: "MUZIK" },
  { id: "172", name: "RISHQA BATRISYIA BINTI RASHIDI", gender: "PEREMPUAN", form: "5 KARYAWAN", group: "5 TARI", field: "TARI" },
  { id: "173", name: "MUHAMMAD AMMAR HAZEEM BIN MOHD ZUHAIRI", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "174", name: "MUHAMMAD AQIL QAZI BIN MOHD ZULHELMI", gender: "LELAKI", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "175", name: "MUHAMMAD HAZIQ RASYID BIN RIDZUAN", gender: "LELAKI", form: "2   MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "176", name: "MUHAMMAD MIKAIL MIERZA BIN MUHAMMAD AKMALUDDIN", gender: "LELAKI", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "177", name: "MUHAMMAD RAYYAN AZZUBAIR BIN MOHAMAD ZAHAIRI", gender: "LELAKI", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "178", name: "NUR ILYAS NASRULLAH BIN ISMAIL", gender: "LELAKI", form: "2 ZAPIN", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "179", name: "SUFI MUHAIMIN BIN SUHAIMI", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "180", name: "UMAR ZAQUAN BIN MOHD NAZARUDDIN", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "181", name: "AIRIS KHAYLA BINTI RADZI", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "182", name: "CINTA ALYAA KHALISA BINTI SOPIAN", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "183", name: "DHIA QAIREEN IRDINA BINTI MOHD FAZLY", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "184", name: "IZZAH NUR JANNAH BINTI RASANA", gender: "PEREMPUAN", form: "2 MASRI", group: "2 PANGGUNG", field: "TEATER" },
  { id: "185", name: "NUR BATRISYIA UMAIRAH BINTI MOHD ZAIRUDDIN", gender: "PEREMPUAN", form: "2 MASRI", group: "2 GEMALAI", field: "TARI" },
  { id: "186", name: "NUR FAKHIRA AIREENA BINTI RASZZI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "187", name: "NUR IWANA QAIREEN BINTI IRWAN", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 PANGGUNG", field: "TEATER" },
  { id: "188", name: "SITI RAHADATUL 'AISY BINTI MASLAN", gender: "PEREMPUAN", form: "2 MASRI", group: "2 PANGGUNG", field: "TEATER" },
  { id: "189", name: "ZARA ISYQ BINTI SHAH REDZA", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "190", name: "SUFI ADRAA AMANDA BINTI MOHD KHUSAIRI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "191", name: "HAZEEQ RAYQAL BIN KHAIRUL MA'ROF", gender: "LELAKI", form: "2 MASRI", group: "2 GEMALAI", field: "TARI" },
  { id: "192", name: "MUHAMMAD ALAUDDIN ZHAFRAN BIN MOHD ZAKI", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "193", name: "MUHAMMAD AMMAR AQEEF BIN MOHAMAD NAJIF", gender: "LELAKI", form: "2 ZAPIN", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "194", name: "MUHAMMAD DANISH HAIKAL BIN HAIRULAZHAR", gender: "LELAKI", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "195", name: "MUHAMMAD HAIQAL ZHARIFF BIN ISMAIL", gender: "LELAKI", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "196", name: "MUHAMMAD HARRAZ IFTIKHAR BIN MOHD HALALI", gender: "LELAKI", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "197", name: "MUHAMMAD QHALIFF AISH BIN FAIRUS", gender: "LELAKI", form: "2 MASRI", group: "2 PANGGUNG", field: "TEATER" },
  { id: "198", name: "ZAFRAN ILYAS BIN ABDUL RAHAMAN", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "199", name: "ADRA ADELIA AMNI BINTI ADNI KHIRULIZZUAN", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "200", name: "AISY NABIHAH BINTI YUNUS", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "202", name: "FIRAZ DHEA ELZAHRA BINTI MOHD YUSLAN", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "203", name: "MAHIRAH FAZLIN BINTI MD FAZLI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "205", name: "NUR ASSYIFATU HAIFA BINTI MOHD ZAINI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "206", name: "NUR DAMIA QISYA BINTI MOHD DINNY", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "207", name: "QASEH XAVIERA BINTI SHAH RULL HAZRY", gender: "PEREMPUAN", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "208", name: "ZARA HASYA BT MOHAMMAD NIZAM", gender: "PEREMPUAN", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "209", name: "ADAM AMSYAR BIN AZRUL", gender: "LELAKI", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "210", name: "EMANNUEL ELMEZ ENCHI ANAK BIDOK", gender: "LELAKI", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "211", name: "IZZ AARIQ BIN AQIB", gender: "LELAKI", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "212", name: "JOHAN ARIFF BIN SAMSUL AFFENDI", gender: "LELAKI", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "213", name: "MUHAMMAD AFIEQ ZAFRY BIN MD ZULFIKRI", gender: "LELAKI", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "214", name: "MUHAMMAD AMIR ASHRAF BIN BUDIMAN", gender: "LELAKI", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "215", name: "MUHAMMAD NUR AIMAN MUHAIMIN BIN MOHD RAFEE", gender: "LELAKI", form: "2 INANG", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "216", name: "YAP MIN SHUEN", gender: "LELAKI", form: "2 INANG", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "217", name: "ALIYA JANNAH BINTI AHMAD FIRDAUS", gender: "PEREMPUAN", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "218", name: "NUR AZZALEA HUSNA BT BORHANODDIN", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "219", name: "NUR HAKIMAH SYADIYAH BINTI SHAHARIL", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "220", name: "PUTRI RAISHA AMANDA BINTI MANSOR", gender: "PEREMPUAN", form: "2 INANG", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "221", name: "RYANA QALEESYA BINTI LOKMAN", gender: "PEREMPUAN", form: "2 INANG", group: "2 GEMALAI", field: "TARI" },
  { id: "222", name: "SITI ALYA HUSNA BINTI MOHD ANUAR", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "223", name: "ZARA ERYNA BINTI AMINUDDIN", gender: "PEREMPUAN", form: "2 INANG", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "224", name: "MUHAMMAD WAFI RIZQIN BIN MOHD NORAZMI", gender: "LELAKI", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "225", name: "AZRIEL JAZLY BIN ZULKIFLI", gender: "LELAKI", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "226", name: "NYGINA BINTI DZULFAMI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "227", name: "ARISSA BINTI JARIR JUANY", gender: "PEREMPUAN", form: "2 INANG", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "228", name: "NUR QASEH UMAIRAH BINTI MOHD FAZLI", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "229", name: "MUHAMMAD NORICK NAUFAL BIN NORAIN", gender: "LELAKI", form: "2 INANG", group: "2 GEMALAI", field: "TARI" },
  { id: "231", name: "AFIF QAIRIN BIN KHAIRUL AZHAR", gender: "LELAKI", form: "2 MASRI", group: "2 GEMALAI", field: "TARI" },
  { id: "232", name: "MUHAMMAD IZZAT AFIF BIN MOHD SHAZRILL", gender: "LELAKI", form: "2 INANG", group: "2 GEMALAI", field: "TARI" },
  { id: "233", name: "MUHAMMAD IMAN RIFQI BIN MOHD NOORAZIUL", gender: "LELAKI", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "234", name: "MUHAMMAD AZAD FARHAT BIN MOHD FAIZAL", gender: "LELAKI", form: "2 ZAPIN", group: "2 GEMERSIK", field: "MUZIK" },
  { id: "235", name: "NUR QURRATU AINI LAILA BINTI MOHD FADLY", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "236", name: "SHARIFAH NURISABELLA DAMIA BINTI SYED MOHD LUQMAN ULHAKIM", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "237", name: "MUHAMMAD HADIF AHZA BIN NORMAN", gender: "LELAKI", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "238", name: "ARYAN DZULQARNAIN BIN MOHD AMIR", gender: "LELAKI", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "239", name: "ABDUL AZIM BIN MESRAN", gender: "LELAKI", form: "2 INANG", group: "2 GEMALAI", field: "TARI" },
  { id: "240", name: "PUTRI IRDINAZAHRA BINTI MOHD RAZI", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "241", name: "ARIANA ZAHRA BINTI ABDULLAH SAIDI", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 GEMALAI", field: "TARI" },
  { id: "242", name: "SHAFFYA ISZARRYN BINTI SHAHARUDIN", gender: "PEREMPUAN", form: "2 INANG", group: "2 PANGGUNG", field: "TEATER" },
  { id: "243", name: "NUR DHIA ASYIFA BINTI MOHD FITRI GADHAFI", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "244", name: "AIMAN HARRIS BIN MOHD AZMI", gender: "LELAKI", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "245", name: "CHE WAN FATNIN AWFIYAH BINTI CHE WAN AZWADI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "246", name: "NUR FATHINI HANNANI BT MOHD FARMIZAL", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 TAMPAK", field: "VISUAL" },
  { id: "247", name: "ANIS MASDIANA BINTI ABDUL HAFIZ", gender: "PEREMPUAN", form: "2 ZAPIN", group: "2 PANGGUNG", field: "TEATER" },
  { id: "248", name: "IZZUSSOLIIHAH BINTI IZZUDIIN", gender: "PEREMPUAN", form: "2 INANG", group: "2 TAMPAK", field: "VISUAL" },
  { id: "249", name: "IMAN NUR DAHIYAH BINTI ZULKIFLI", gender: "PEREMPUAN", form: "2 MASRI", group: "2 TAMPAK", field: "VISUAL" },
  { id: "250", name: "MUHAMMAD AQIL DANISH BIN MUHAMMAD SAIFUL IZWANSH", gender: "LELAKI", form: "4 SUTERA", group: "4 VISUAL", field: "VISUAL" },
  { id: "251_F1", name: "AHMAD ADAM BIN NOOR AZAM", gender: "LELAKI", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "252_F1", name: "AMMAR KHALISH BIN JONUR SHAHRIZAL", gender: "LELAKI", form: "1 BALADA", group: "1 PANGGUNG", field: "TEATER" },
  { id: "253_F1", name: "HADIF ZAYANI BIN AZNISYAM", gender: "LELAKI", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "254_F1", name: "MUHAMMAD DANIEL HARITH BIN MOHD TAUFIQ", gender: "LELAKI", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "255_F1", name: "MUHAMMAD IZZ ZAFRAN BIN MOHD FERDAUS", gender: "LELAKI", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "256_F1", name: "MUHAMMAD MUQRI JAAD BIN MOHD JALAINI", gender: "LELAKI", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "257_F1", name: "MUHAMMAD NAZMIE BIN SAMAT", gender: "LELAKI", form: "1 BALADA", group: "1 GEMALAI", field: "TARI" },
  { id: "258_F1", name: "MUHAMMAD NURZIQRI BIN MOHD HELMY RIZAL", gender: "LELAKI", form: "1 BALADA", group: "1 GEMALAI", field: "TARI" },
  { id: "259_F1", name: "MUHAMMAD UKAIL REZQALLAH BIN MOHD SHAMZUAR", gender: "LELAKI", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "260_F1", name: "YAP MIN SIANG", gender: "LELAKI", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "261_F1", name: "AIRINA ASSOFEA BINTI AMIR ARAFAT", gender: "PEREMPUAN", form: "1 BALADA", group: "1 PANGGUNG", field: "TEATER" },
  { id: "262_F1", name: "AIRIS FARISAH BINTI AZMIN FADLI", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "263_F1", name: "AUNI SOFEA RAMADHANI BINTI MOHD JAIZI", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "265_F1", name: "KHAYLA AMANDA QUAH BINTI KHAIRUL ASRI", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "266_F1", name: "MUZFIRAH AUNI BINTI MUSA", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "267_F1", name: "NUR AWATIF BINTI FAEZAL", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "268_F1", name: "NUR AYEESHA AZZALEEA BINTI MOHAMED MUKHRIZ", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMALAI", field: "TARI" },
  { id: "269_F1", name: "NUR DELISHA ADRIANA BINTI SUPIAN", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "270_F1", name: "NUR HANA HUMAIRA BINTI MUHAMMAD NUR FIKRI", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "271_F1", name: "NUR IRDINA ZAHRA BINTI MOHAMAD NOOR IRWAN", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "272_F1", name: "NUR KHAYRA BINTI MOHD HAFIZ", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "273_F1", name: "NUR ZARA DIANDRA BINTI JAMALY", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "274_F1", name: "NURUL HASYA ZAFIRAH BINTI MOHAMAD HAFIZZUL", gender: "PEREMPUAN", form: "1 BALADA", group: "1 PANGGUNG", field: "TEATER" },
  { id: "275_F1", name: "SAJINIEKA AP RAJINIKAN", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMALAI", field: "TARI" },
  { id: "276_F1", name: "SAURA HANNANI BINTI MOHD ADZWAN", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "277_F1", name: "AMMAR AMANI BIN AZLAN", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "278_F1", name: "MOHAMMAD FAIQ KHALISH BIN MOHAMMAD FAISAL", gender: "LELAKI", form: "1 JAZZ", group: "1 PANGGUNG", field: "TEATER" },
  { id: "279_F1", name: "MOHAMAD FIRAS AMSYAR BIN MOHAMAD RABANI", gender: "LELAKI", form: "1 JAZZ", group: "1 PANGGUNG", field: "TEATER" },
  { id: "280_F1", name: "MUHAMAD FIRAS RAMADAN BIN MOHD HANIF", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "281_F1", name: "MUHAMMAD ADNAF AIMAN BIN ABD RAUF", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "282_F1", name: "MUHAMMAD AISY HAFIY BIN MOHD NAZRI", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "283_F1", name: "MUHAMMAD DAIM DANIAL BIN ISMAIL", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "284_F1", name: "MUHAMMAD ISKANDAR BIN MUHAMAD HANAFEE", gender: "LELAKI", form: "1 JAZZ", group: "1 TAMPAK", field: "VISUAL" },
  { id: "285_F1", name: "MUHAMMAD IZZHAIDHAR BIN MOHD HARDI", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "286_F1", name: "MUHAMMAD RAYYAN SUFYAN BIN RIZWAN", gender: "LELAKI", form: "1 JAZZ", group: "1 PANGGUNG", field: "TEATER" },
  { id: "287_F1", name: "MUHAMMAD ZARIF FIKRI BIN SABERI", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "288_F1", name: "Q MUHAMMAD HALID AL WALID BIN MOHD SUHAIMI", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "289_F1", name: "AIRA KARMILA BINTI MOHD AZHARI", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "290_F1", name: "AUNI RIZQAH BINTI AHMAD RIDZUAN", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "291_F1", name: "EVA JASLIN QISTINA BINTI MAHATHIR", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "292_F1", name: "NORUL IMAN FATHONAH BINTI MOHAMMAD AFDHALUDDIN", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 TAMPAK", field: "VISUAL" },
  { id: "293_F1", name: "NUR DAMIA HANNA BINTI HAMRI", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 PANGGUNG", field: "TEATER" },
  { id: "294_F1", name: "NUR IMAN SAHARA BINTI SHAFIQ ALI", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 PANGGUNG", field: "TEATER" },
  { id: "295_F1", name: "NUR QHAILA MAISARA BINTI HERIYANTO", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "296_F1", name: "NUR SYIFA ADELIA BINTI MOHD ZAMRI", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 TAMPAK", field: "VISUAL" },
  { id: "297_F1", name: "NURHANNINI QAIRINA BINTI MOHAMAD NIZAIRIN", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMALAI", field: "TARI" },
  { id: "298_F1", name: "NURQURRATUL QYRA QIRDYNA BINTI MOHD AZUAR", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 TAMPAK", field: "VISUAL" },
  { id: "299_F1", name: "QISTINA ELENA BINTI YUSOFF", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "300_F1", name: "QISYA ELENA BINTI YUSOFF", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "302_F1", name: "HARITH AZFAR BIN ABDUL MALIK", gender: "LELAKI", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "303_F1", name: "IZZ RIZQI BIN AHMAD SANI", gender: "LELAKI", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "304_F1", name: "MIFZAL KHALISH BIN MUHAMMAD KHIZIR", gender: "LELAKI", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "305_F1", name: "MUHAMMAD EZZAT ADAM BIN EZIHAN", gender: "LELAKI", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "306_F1", name: "MUHAMMAD NAZIM SALAHUDDIN BIN SHAWAL", gender: "LELAKI", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" },
  { id: "307_F1", name: "MUHAMMAD OZIL IQMAL BIN SYUKOR", gender: "LELAKI", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "308_F1", name: "MUHAMMAD SYAHMI IKHWAN BIN MD LIZWAN", gender: "LELAKI", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" },
  { id: "309_F1", name: "NOAH MALIK BIN MAT NOR", gender: "LELAKI", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "310_F1", name: "AIRIS ERYNA BINTI MOHD FADZLI", gender: "PEREMPUAN", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "311_F1", name: "ARFA IRDINA BINTI AZLAN", gender: "PEREMPUAN", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "312_F1", name: "ERYNA BATRISYA BINTI MOHD JIHAN", gender: "PEREMPUAN", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" },
  { id: "313_F1", name: "NUR AISYAH SAFIYYA BINTI MOHD KHAFIZ", gender: "PEREMPUAN", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "314_F1", name: "PUTERI NOURA NILOUFAR BINTI MUHAMMAD RIDZUAN", gender: "PEREMPUAN", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "315_F1", name: "ABSAREENA AL-AFLAQ BINTI MOHD FARHAN AL-FIRDAUS", gender: "PEREMPUAN", form: "1 BALADA", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "316_F1", name: "SYAZA AMNEE BINTI SAIFUL AZAM", gender: "PEREMPUAN", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "317_F1", name: "HAYFA AZALEA BINTI FYTHULLAH", gender: "PEREMPUAN", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "318_F1", name: "MYA ZARRA AMANDA BINTI MOHD SHAHREDZAL KENNETH", gender: "PEREMPUAN", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" },
  { id: "319_F1", name: "UMMUL LAILA ELUIRA BINTI MOHD BAHARUDDIN", gender: "PEREMPUAN", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "320_F1", name: "NUR SYA’ADAWIAH BINTI WALEK FANDI", gender: "PEREMPUAN", form: "1 TANGO", group: "1 TAMPAK", field: "VISUAL" },
  { id: "321_F1", name: "HANNAN BASHEERA BINTI HAIRUS", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 TAMPAK", field: "VISUAL" },
  { id: "322_F1", name: "ATHENA YIE YU THONG", gender: "PEREMPUAN", form: "1 BALADA", group: "1 TAMPAK", field: "VISUAL" },
  { id: "323_F1", name: "ADNI NISRINA BINTI MUHAMAD RUSLAN", gender: "PEREMPUAN", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "324_F1", name: "NUR DAYANA ZAFIRAH BINTI MOHD FAIZUL", gender: "PEREMPUAN", form: "1 TANGO", group: "1 PANGGUNG", field: "TEATER" },
  { id: "325_F1", name: "AARON AFIF BIN ANDY", gender: "LELAKI", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "326_F1", name: "ZAFRI HADEE BIN ZAINAL", gender: "LELAKI", form: "1 JAZZ", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "327_F1", name: "KHALISH BIN MOHD SHAHID", gender: "LELAKI", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "328_F1", name: "FIRAS ABUWASIM BIN NORDIN", gender: "LELAKI", form: "1 TANGO", group: "1 GEMERSIK", field: "MUZIK" },
  { id: "329_F1", name: "MUHAMMAD ALHAM NORFAWWAZ BIN MOHD AMRILNORMAN", gender: "LELAKI", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" },
  { id: "330_F1", name: "DARIS NUFAIL RAYYAN BIN MOHD YAMIN", gender: "LELAKI", form: "1 BALADA", group: "1 GEMALAI", field: "TARI" },
  { id: "331_F1", name: "MUHAMMAD IZZAT RIZQI BIN MOHD RAZLAN", gender: "LELAKI", form: "1 TANGO", group: "1 GEMALAI", field: "TARI" }
];
